### PR TITLE
Update background.js - Shift click reloads bybassing cache

### PR DESCRIPTION
**Pull request by Woolloff**
Also fixes tab id from previous commit.

### CODE REVIEW

**Comment by Woolloff** [comment]
There is no event object passed to the handler - I am going to add some code to handle the keyboard events a different way.

**Comment by trubens** [comment]
Thanks for the fix, but the `event` variable is unavailable. Because of this it will crash. Can you figure out a way to get the hold of the event?

**Comment by Woolloff** [comment]
Yes, I have an alternative solution.

It is not perfect but it is the best we can do without support for checking the modifiers directly in the API. It will work if the user presses the modifier key anywhere over the window when the window has focus. It will not work if the user presses the modifier key and the window doesn't have focus. 

It seems keyboard and mouse events are only accessible to content scripts (not background scripts directly) and content scripts only have access to the mouse / keyboard within the window bounds while the tab is focused.

I will update the code here shortly with this option.

**Comment by Woolloff** [comment]
Those are all the changes from my side.

**Comment by Woolloff** [comment]
Also, I updated the manifest version to 1.6 although I see you already created a fixed version for 1.6, so this one should be 1.7.

**Comment by Woolloff** [comment]
Just to confirm, I fully tested this, so it should be fully functional and bug free.

**Comment by trubens** [comment]
Thanks! I would love a more native approach, but we can change that when event is better implemented.

**Pull request merged**
